### ISSUE TITLE
Incorrect dependency resolve...

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/acbs#4]
Don't know how to explain this but... Here you go...

```
root:/usr/lib/abbs/repo# acbs-build -d shared-mime-info
---------------------------------------Welcome to ACBS - 20170103---------------------------------------
[DEBUG]: Search Path: /usr/lib/abbs/repo
[INFO]: Start building extra-misc/shared-mime-info
[DEBUG]: Found pm_backends: ['/usr/lib/acbs/acbs/pm/dpkg.sh']
[INFO]: Checking for dependencies, this may take a while...
[DEBUG]: Searching dependencies: ['intltool', 'glib', 'libxml2']
[DEBUG]: PM Backend: dpkg CMD: pm_exists('intltool') Res: False
[DEBUG]: PM Backend: dpkg CMD: pm_exists('glib') Res: False
[DEBUG]: PM Backend: dpkg CMD: pm_exists('libxml2') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_repoquery('glib') Res: False
[DEBUG]: PM Backend: dpkg CMD: pm_repoquery('intltool') Res: False
[INFO]: Building in-tree dependencies: glib intltool
[DEBUG]: New build thread started for glib
[DEBUG]: Search Path: /usr/lib/abbs/repo
[INFO]: Start building base-libs/glib
[DEBUG]: Found pm_backends: ['/usr/lib/acbs/acbs/pm/dpkg.sh']
[INFO]: Checking for dependencies, this may take a while...
[DEBUG]: Searching dependencies: ['python-2', 'docbook-xml', 'gtk-doc', 'libxslt', 'pkg-config', 'pcre', 'libffi', 'elfutils']
[DEBUG]: PM Backend: dpkg CMD: pm_exists('python-2') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('docbook-xml') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('gtk-doc') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('libxslt') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('pkg-config') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('pcre') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('libffi') Res: 
[DEBUG]: PM Backend: dpkg CMD: pm_exists('elfutils') Res: 
[INFO]: All dependencies are met. Continue.
[DEBUG]: Checksums: []
[WARN]: No checksum is found! This is discouraged!
[DEBUG]: Source location: /var/cache/acbs/tarballs/glib-2.50.2.tar.xz, Shadow link: /var/cache/acbs/build/acbs.rri5k2a9/glib-2.50.2.tar.xz
[WARN]: ACBS cannot find libmagic bindings, will use bundled one instead.
[DEBUG]: Traceback:
  File "/bin/acbs-build", line 91, in <module>
    main()
  File "/bin/acbs-build", line 42, in main
    acbs_instance.build()
  File "/usr/lib/acbs/acbs/mainflow.py", line 103, in build
    self.build_single_pkg(matched_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 169, in build_single_pkg
    self.build_main(single_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 148, in build_main
    self.new_build_thread(try_build)
  File "/usr/lib/acbs/acbs/mainflow.py", line 193, in new_build_thread
    'Sub-build process building \033[36m{}\033[0m \033[93mfailed!\033[0m'.format(sub_pkg)) from ex

Traceback (most recent call last):
  File "/usr/lib/acbs/acbs/src_process.py", line 60, in file_type
    import magic
ModuleNotFoundError: No module named 'magic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/acbs/acbs/mainflow.py", line 190, in new_build_thread
    return sub_thread.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/acbs/acbs/mainflow.py", line 179, in slave_thread_build
    return new_build_instance.build()
  File "/usr/lib/acbs/acbs/mainflow.py", line 103, in build
    self.build_single_pkg(matched_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 169, in build_single_pkg
    self.build_main(single_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 154, in build_main
    tmp_dir_loc.append(SourceProcessor(self.pkg_data, self).process())
  File "/usr/lib/acbs/acbs/src_process.py", line 55, in process
    self.decomp_file()
  File "/usr/lib/acbs/acbs/src_process.py", line 95, in decomp_file
    file_type_name = self.file_type()
  File "/usr/lib/acbs/acbs/src_process.py", line 64, in file_type
    import acbs.magic as magic
  File "/usr/lib/acbs/acbs/magic.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/usr/lib/python3.6/ctypes/__init__.py", line 357, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 362, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: magic_open

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bin/acbs-build", line 91, in <module>
    main()
  File "/bin/acbs-build", line 42, in main
    acbs_instance.build()
  File "/usr/lib/acbs/acbs/mainflow.py", line 103, in build
    self.build_single_pkg(matched_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 169, in build_single_pkg
    self.build_main(single_pkg)
  File "/usr/lib/acbs/acbs/mainflow.py", line 148, in build_main
    self.new_build_thread(try_build)
  File "/usr/lib/acbs/acbs/mainflow.py", line 193, in new_build_thread
    'Sub-build process building \033[36m{}\033[0m \033[93mfailed!\033[0m'.format(sub_pkg)) from ex
acbs.utils.ACBSGeneralError: Sub-build process building glib failed!
```

**Comment by liushuyu** [comment]
Fixed in ca326eb
